version: '3'
services:
  db:
    image: postgres:14
    restart: always
    container_name: postgres
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=rustwebdev
      - POSTGRES_PASSWORD=rustwebdev

  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - default
    ports:
      - "3030:3030"

volumes:
  db-store: