### 最初のサンプルHTTPリクエスト
GET http://127.0.0.1:3030/questions

### クエリパラメータの検証
GET http://127.0.0.1:3030/questions?limit=10&offset=0

### CORS設定確認用
OPTIONS http://127.0.0.1:3030/questions
Access-Control-Request-Method: GET 
Access-Control-Request-Headers: content-type

### Question追加用
POST http://127.0.0.1:3030/questions
Content-Type: application/json

{
    "title": "New Question",
    "content": "How does this shit work again?",
    "tags": ["normal", "high"]
}

### 質問文の修正
PUT http://127.0.0.1:3030/questions/1
Content-Type: application/json

{
    "id": 1,
    "title": "Updated Title",
    "content": "[Updated] How does this work again?",
    "tags": ["sports"]
}

### 質問文の削除
DELETE http://127.0.0.1:3030/questions/1

### 解答の追加
POST http://127.0.0.1:3030/answers
Content-Type: application/json

{
    "title": "New Question",
    "content": "How does this work again?",
    "question_id": 1
}
